name: Sync code to GitCode

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Name of repository'
        type: string
        required: true
      branch:
        description: 'Name of default branch'
        type: string
        default: 'main'
      remote:
        description: 'Name of remote site'
        # TODO(Qiming): make this a choice
        type: string
        default: 'gitcode.com' 
    secrets:
      GITCODE_SSH_KEY:
        description: 'SSH private key for gitcode'
        required: true

  workflow_call:
    inputs:
      repository:
        description: 'Name of repository'
        type: string
        required: true
      branch:
        description: 'Name of default branch'
        type: string
        default: 'main'
      remote:
        description: 'Name of remote site'
        type: string
        default: 'gitcode.com'
    secrets:
      GITCODE_SSH_KEY:
        description: 'SSH private key for gitcode'
        required: true

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      REMOTE: ${{ inputs.remote }}
      REPO: ${{ inputs.repository }}
      BRANCH: ${{ inputs.branch }}
    steps:
      - id: setup-ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GITCODE_SSH_KEY }}

      - id: add-know-hosts
        run: |
          ssh-keyscan ${REMOTE} >> ~/.ssh/known_hosts

      - id: clone
        run: |
          git clone git@${REMOTE}:flagos-ai/${REPO}.git ${REPO}

      - id: rebase-and-push
        run: |
          cd ${REPO}
          git checkout ${BRANCH}
          git remote add github https://github.com/flagos-ai/${REPO}.git
          git fetch github
          git status
          git rebase github/${BRANCH}
          git config --global user.name weixin_39841130
          git config --global user.email weixin_39841130@noreply.gitcode.com
          git push -u origin ${BRANCH} -f
